/*------------------------------------------------------------*



*--------------------Procedure Description--------------------*
| mtmdutl.cpp   Earl Cox  04/01/93  This files contains the   |
| general utility methods associated with the model class.    |
| These are grouped here instead of in their own files for    |
| management and maintainability.                             |
*----------------Modification Audit/Change Log----------------*
| Rev  Sar                                                    |
| No   Code  Date      Rellvl  Mod  Description               |
| --   ----- --------  ------  ---  --------------------------|
|                                                             |
*-------------------------------------------------------------*/
char*  MtsVersion()   {return("FzyLib 1.0A");}
char*  MtsLicense()   {return("0000.00");}
char*  MtsOwner()     {return("The Great Widget and Wradget Corp.");}
